import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

const pages = [
  { name: 'Home', path: '/' },
  { name: 'About', path: '/about' },
  { name: 'Blog', path: '/blog' },
  { name: 'Youtube', path: 'https://www.youtube.com/kuzeykose' },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto max-w-2xl lg:max-w-6xl p-6">
          <nav className="flex gap-6 mx-auto border rounded-xl px-2 py-1 bg-zinc-200 max-w-fit p">
            {pages.map((page) => (
              <Link href={page.path} className="cursor-pointer px-2 py-1 rounded-lg hover:bg-zinc-300">
                {page.name}
              </Link>
            ))}
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
