import { PieceDef } from './pieces'
import { C } from './palette'
import { skyBackdrop } from './art-landmarks'
import { cloud } from './art-street'
import { beachUmbrella, beachgoers, cyclone, parachuteJump, seagull, wonderFrame, wonderWheel } from './art-brooklyn'
import { HUB_Y, WHEEL } from './pieces-brooklyn'
import {
  beachcomber,
  boardwalk,
  coneyBackdrop,
  lifeguardChair,
  lunaGate,
  mermaidParade,
  nathans,
  polarPlunge,
  sandcastle,
  strollers,
  surf,
  thunderbolt,
} from './art-coney'

// Coney Island, looking north from the Atlantic: the surf and the beach in
// front, the boardwalk, and the rides lined up behind.
export const CONEY: PieceDef[] = [
  {
    id: 'ci-sky',
    label: 'A beach day sky',
    art: (s) => skyBackdrop(s, false),
    nightArt: (s) => skyBackdrop(s, true),
    w: 11.6,
    h: 7.4,
    x: 0,
    z: -4.75,
    sameArtAs: 'sky',
    order: 0,
    seed: 9201,
    glow: true,
    sky: true,
  },
  {
    id: 'ci-cloud',
    label: 'A cloud',
    art: cloud,
    w: 1.9,
    h: 0.8,
    x: 3.6,
    z: 0,
    parent: 'ci-sky',
    offset: [3.6, 5.7, 0.12],
    sameArtAs: 'cloud-left',
    order: 0,
    seed: 9202,
    padBottom: true,
    bob: { amp: 0.04, speed: 0.45 },
    poke: 'lift',
    sky: true,
  },
  {
    id: 'ci-far',
    label: 'Brooklyn, behind the boardwalk',
    art: coneyBackdrop,
    w: 12.6,
    h: 3.4,
    x: 0,
    z: -4.3,
    order: 0.08,
    seed: 9203,
    glow: true,
  },
  {
    id: 'ci-parachute',
    label: 'The Parachute Jump',
    art: parachuteJump,
    w: 1.9,
    h: 5.2,
    x: -5.4,
    z: -3.4,
    sameArtAs: 'bk-parachute',
    order: 0.12,
    seed: 9204,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ci-thunderbolt',
    label: 'The Thunderbolt',
    art: thunderbolt,
    w: 3.0,
    h: 2.4,
    x: -2.7,
    z: -2.6,
    order: 0.16,
    seed: 9205,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ci-wheel-frame',
    label: "Deno's Wonder Wheel",
    art: wonderFrame,
    w: 3.4,
    h: 2.8,
    x: 0.9,
    z: -2.8,
    sameArtAs: 'bk-wheel-frame',
    order: 0.14,
    seed: 9206,
    glow: true,
    poke: 'tilt',
    startles: 'ci-wheel',
  },
  {
    id: 'ci-wheel',
    label: "Deno's Wonder Wheel",
    art: wonderWheel,
    w: WHEEL,
    h: WHEEL,
    x: 0.9,
    z: 0,
    parent: 'ci-wheel-frame',
    offset: [0, HUB_Y - WHEEL / 2, 0.06],
    sameArtAs: 'bk-wheel',
    order: 0.14,
    seed: 9207,
    glow: true,
    padBottom: true,
    poke: 'spin',
    spin: { at: [WHEEL / 2, WHEEL / 2], idle: 0.18 },
    pokeOnOpen: true,
  },
  {
    id: 'ci-cyclone',
    label: 'The Cyclone, since 1927',
    art: cyclone,
    w: 4.4,
    h: 2.3,
    x: 4.8,
    z: -2.3,
    sameArtAs: 'bk-cyclone',
    order: 0.18,
    seed: 9208,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ci-nathans',
    label: "Nathan's Famous, on Surf Avenue",
    art: nathans,
    w: 2.8,
    h: 1.8,
    x: -4.7,
    z: -0.7,
    order: 0.3,
    seed: 9209,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ci-luna',
    label: 'The way into Luna Park',
    art: lunaGate,
    w: 2.6,
    h: 2.1,
    x: 2.9,
    z: -0.85,
    order: 0.32,
    seed: 9210,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ci-strollers',
    label: 'A stroll on the boardwalk',
    art: strollers,
    w: 2.2,
    h: 1.35,
    x: -1.6,
    z: 0.45,
    order: 0.5,
    seed: 9211,
    poke: 'tilt',
  },
  {
    id: 'ci-parade',
    label: 'The Mermaid Parade',
    art: mermaidParade,
    w: 2.6,
    h: 1.7,
    x: 1.9,
    z: 1.4,
    seasons: ['summer'],
    order: 0.6,
    seed: 9212,
    poke: 'lift',
  },
  {
    id: 'ci-boardwalk',
    label: 'The Riegelmann Boardwalk',
    art: boardwalk,
    w: 13.0,
    h: 0.92,
    x: 0,
    z: 0.8,
    order: 0.56,
    seed: 9213,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ci-lifeguard',
    label: 'The lifeguard chair',
    art: lifeguardChair,
    w: 1.2,
    h: 2.0,
    x: -5.8,
    z: 1.9,
    order: 0.66,
    seed: 9214,
    poke: 'tilt',
  },
  {
    id: 'ci-umbrella-1',
    label: 'A day at the beach',
    art: (s) => beachUmbrella(s, C.red),
    w: 1.2,
    h: 1.3,
    x: -3.1,
    z: 2.2,
    sameArtAs: 'bk-umbrella-1',
    seasons: ['summer'],
    order: 0.7,
    seed: 9215,
    poke: 'tilt',
  },
  {
    id: 'ci-umbrella-2',
    label: 'A day at the beach',
    art: (s) => beachUmbrella(s, '#3f6fb0'),
    w: 1.2,
    h: 1.3,
    x: 3.7,
    z: 2.4,
    sameArtAs: 'bk-umbrella-2',
    seasons: ['summer'],
    order: 0.72,
    seed: 9216,
    poke: 'tilt',
  },
  {
    id: 'ci-beach',
    label: 'Beachgoers',
    art: beachgoers,
    w: 1.5,
    h: 1.25,
    x: -0.9,
    z: 2.6,
    scale: 1.2,
    sameArtAs: 'bk-beach',
    seasons: ['summer'],
    order: 0.76,
    seed: 9217,
    poke: 'tilt',
  },
  {
    id: 'ci-sandcastle',
    label: 'A sandcastle',
    art: sandcastle,
    w: 1.45,
    h: 1.0,
    x: 1.5,
    z: 2.9,
    seasons: ['summer'],
    order: 0.8,
    seed: 9218,
    poke: 'tilt',
  },
  {
    id: 'ci-comber',
    label: 'A beachcomber, listening for treasure',
    art: beachcomber,
    w: 1.2,
    h: 1.3,
    x: 0.9,
    z: 2.6,
    seasons: ['spring', 'autumn', 'winter'],
    order: 0.78,
    seed: 9219,
    poke: 'tilt',
  },
  {
    id: 'ci-gull',
    label: 'A seagull, after your fries',
    art: seagull,
    w: 0.7,
    h: 0.5,
    x: 5.6,
    z: 2.5,
    scale: 1.1,
    sameArtAs: 'bk-gull',
    order: 0.82,
    seed: 9220,
    poke: 'lift',
  },
  {
    id: 'ci-plunge',
    label: 'The Polar Bear Plunge, on New Year’s Day',
    art: polarPlunge,
    w: 2.6,
    h: 1.3,
    x: -1.2,
    z: 3.35,
    seasons: ['winter'],
    order: 0.86,
    seed: 9221,
    poke: 'lift',
  },
  {
    id: 'ci-surf',
    label: 'The Atlantic',
    art: surf,
    w: 13.0,
    h: 0.45,
    x: 0,
    z: 3.8,
    order: 0.9,
    seed: 9222,
    bob: { amp: 0.03, speed: 1.2, sway: 0.004 },
    poke: 'lift',
  },
]
