import { PieceDef } from './pieces'
import { skyBackdrop } from './art-landmarks'
import { farSkyline } from './art-buildings'
import { hotDogCart, taxi } from './art-street'
import {
  POLE_TOP,
  TOWERS,
  ZIPPER,
  billboardTower,
  hotelTower,
  oneTimesSquare,
  paramountBuilding,
  recruitingStation,
  theaterMarquee,
  timesBall,
  tktsSteps,
  tourists,
} from './art-times'

// How far the ball comes down its pole.
const DROP = 0.75
const CONFETTI = ['#ff4f8b', '#ffd23f', '#3fc1ff', '#7cff6b', '#ffffff', '#ff8a3d', '#b48cff']

const HEADLINES = [
  'PAPER CITY POPS UP IN MIDTOWN',
  'BALL DROP REHEARSAL TONIGHT',
  'PIZZA RAT SPOTTED ON THE STEPS',
  'SQUIRREL MAKES OFF WITH ACORN IN CENTRAL PARK',
  'WONDER WHEEL STILL TURNING',
  'CHERRY BLOSSOMS IN BROOKLYN',
]

const cab = (id: string, x: number, z: number, seed: number, order: number): PieceDef => ({
  id,
  label: 'Yellow cab',
  art: taxi,
  w: 2.0,
  h: 0.95,
  x,
  z,
  sameArtAs: 'taxi',
  order,
  seed,
  glow: true,
  poke: 'drive',
})

// The fourth spread: Times Square at dusk, looking south down the bowtie.
export const TIMES: PieceDef[] = [
  {
    id: 'ts-sky',
    label: 'Dusk over Midtown',
    art: (s) => skyBackdrop(s, false, true),
    nightArt: (s) => skyBackdrop(s, true),
    w: 11.6,
    h: 7.4,
    x: 0,
    z: -4.75,
    sameArtAs: 'bk-sky',
    order: 0,
    seed: 4101,
    glow: true,
    sky: true,
  },
  {
    id: 'ts-far',
    label: 'Midtown',
    art: farSkyline,
    w: 12.6,
    h: 5.0,
    x: 0,
    z: -4.25,
    sameArtAs: 'far',
    order: 0.08,
    seed: 4102,
    glow: true,
  },
  {
    id: 'ts-paramount',
    label: 'The Paramount Building',
    art: paramountBuilding,
    w: 1.9,
    h: 4.8,
    x: -2.4,
    z: -3.6,
    order: 0.1,
    seed: 4201,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ts-one',
    label: 'One Times Square',
    art: oneTimesSquare,
    w: 1.7,
    h: 5.65,
    x: 0,
    z: -3.3,
    order: 0.12,
    seed: 4202,
    glow: true,
    poke: 'tilt',
    startles: 'ts-ball',
    ticker: { text: HEADLINES.map((h) => `★ ${h} `).join(''), at: [ZIPPER.x, ZIPPER.y], w: ZIPPER.w, h: ZIPPER.h },
  },
  {
    id: 'ts-ball',
    label: 'The New Year’s Eve ball',
    art: timesBall,
    w: 0.5,
    h: 0.5,
    x: 0,
    z: 0,
    parent: 'ts-one',
    offset: [0, POLE_TOP - 0.3, 0.06],
    order: 0.12,
    seed: 4203,
    glow: true,
    padBottom: true,
    poke: 'drop',
    drop: DROP,
    // Confetti bursts round where it lands.
    petals: {
      from: [
        [0.25, 0.25 - DROP, 0.9],
        [0.25, 0.9 - DROP, 0.7],
      ],
      colors: CONFETTI,
      count: 96,
      confetti: true,
    },
    pokeOnOpen: true,
  },
  {
    id: 'ts-tower-left',
    label: 'Billboards on Broadway',
    art: (s) => billboardTower(s, TOWERS[0].base, TOWERS[0].boards),
    w: 2.2,
    h: 4.3,
    x: -4.4,
    z: -2.0,
    order: 0.18,
    seed: 4204,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ts-tower-right',
    label: 'The market screens',
    art: (s) => billboardTower(s, TOWERS[1].base, TOWERS[1].boards),
    w: 2.2,
    h: 4.1,
    x: 3.1,
    z: -3.0,
    order: 0.16,
    seed: 4205,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ts-hotel',
    label: 'A hotel in lights',
    art: hotelTower,
    w: 2.35,
    h: 4.2,
    x: -6.4,
    z: -0.8,
    ry: 0.6,
    order: 0.24,
    seed: 4206,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ts-candy',
    label: 'Signs all the way up',
    art: (s) => billboardTower(s, TOWERS[3].base, TOWERS[3].boards),
    w: 2.4,
    h: 4.2,
    x: 6.4,
    z: -0.8,
    ry: -0.6,
    order: 0.24,
    seed: 4207,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ts-recruit',
    label: 'The recruiting station’s neon flag',
    art: recruitingStation,
    w: 1.4,
    h: 1.1,
    x: -1.2,
    z: -0.4,
    order: 0.45,
    seed: 4208,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ts-theater',
    label: 'A Broadway theater',
    art: theaterMarquee,
    w: 2.4,
    h: 3.0,
    x: 4.6,
    z: 0.5,
    order: 0.55,
    seed: 4209,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ts-tkts',
    label: 'The red steps at Duffy Square',
    art: tktsSteps,
    w: 3.4,
    h: 1.9,
    x: 0.6,
    z: 1.0,
    order: 0.6,
    seed: 4210,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ts-tourists',
    label: 'Tourists (and a Lady Liberty)',
    art: tourists,
    w: 2.6,
    h: 1.5,
    x: -3.6,
    z: 1.8,
    order: 0.7,
    seed: 4211,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'ts-cart',
    label: 'Hot dog cart',
    art: hotDogCart,
    w: 1.4,
    h: 1.6,
    x: -5.7,
    z: 2.4,
    scale: 1.15,
    sameArtAs: 'cart',
    order: 0.72,
    seed: 4212,
    poke: 'tilt',
  },
  cab('ts-cab-1', 2.4, 2.9, 4213, 0.8),
  cab('ts-cab-2', -1.5, 3.4, 4214, 0.84),
]
