import { PieceDef } from './pieces'
import { C } from './palette'
import { skyBackdrop } from './art-landmarks'
import { brownstones, farSkyline, BROOKLYN_HOUSES } from './art-buildings'
import { cloud } from './art-street'
import {
  CAROUSEL_POLES,
  GARDEN_BLOSSOMS,
  beachUmbrella,
  barclaysCenter,
  beachgoers,
  botanicGarden,
  carousel,
  carouselHorse,
  coffeeCup,
  cyclist,
  cyclone,
  dumbo,
  grandArmyArch,
  iceCreamTruck,
  mural,
  parkTree,
  parachuteJump,
  seagull,
  welcomeSign,
  wonderFrame,
  wonderWheel,
} from './art-brooklyn'

// Where the Wonder Wheel's hub sits on its frame, and the wheel's size.
const HUB_Y = 2.62
const WHEEL = 3.3

const horse = (i: number, body: string, saddle: string): PieceDef => ({
  id: `bk-horse-${i}`,
  label: 'Carousel horse',
  art: (s) => carouselHorse(s, body, saddle, i % 2 ? -1 : 1),
  w: 0.7,
  h: 0.75,
  x: CAROUSEL_POLES[i] - 1.5,
  z: 0,
  parent: 'bk-carousel',
  offset: [CAROUSEL_POLES[i] - 1.5, 0.78, 0.05],
  order: 0.6,
  seed: 2300 + i,
  padBottom: true,
  bob: { amp: 0.09, speed: 1.9 },
  poke: 'lift',
})

// The second spread: Brooklyn at golden hour.
export const BROOKLYN: PieceDef[] = [
  {
    id: 'bk-sky',
    label: 'Sunset over Brooklyn',
    art: (s) => skyBackdrop(s, false, true),
    nightArt: (s) => skyBackdrop(s, true),
    w: 11.6,
    h: 7.4,
    x: 0,
    z: -4.75,
    order: 0,
    seed: 2101,
    glow: true,
    sky: true,
  },
  {
    id: 'bk-cloud',
    label: 'A cloud',
    art: cloud,
    w: 1.9,
    h: 0.8,
    x: -3.6,
    z: 0,
    parent: 'bk-sky',
    offset: [-3.6, 5.3, 0.12],
    sameArtAs: 'cloud-left',
    order: 0,
    seed: 2104,
    padBottom: true,
    bob: { amp: 0.04, speed: 0.45 },
    poke: 'lift',
    sky: true,
  },
  {
    id: 'bk-far',
    label: 'Manhattan, across the river',
    art: farSkyline,
    w: 12.6,
    h: 5.0,
    x: 0,
    z: -4.25,
    sameArtAs: 'far',
    order: 0.08,
    seed: 2102,
    glow: true,
  },
  {
    id: 'bk-dumbo',
    label: 'DUMBO and the Manhattan Bridge',
    art: dumbo,
    w: 5.4,
    h: 5.0,
    x: -0.9,
    z: -3.2,
    order: 0.16,
    seed: 2201,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'bk-wheel-frame',
    label: 'The Wonder Wheel',
    art: wonderFrame,
    w: 3.4,
    h: 2.8,
    x: 6.55,
    z: 1.15,
    ry: -0.45,
    order: 0.66,
    seed: 2202,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'bk-wheel',
    label: 'The Wonder Wheel',
    art: wonderWheel,
    w: WHEEL,
    h: WHEEL,
    x: 6.55,
    z: 0,
    parent: 'bk-wheel-frame',
    offset: [0, HUB_Y - WHEEL / 2, 0.06],
    order: 0.66,
    seed: 2203,
    glow: true,
    padBottom: true,
    poke: 'spin',
    spin: { at: [WHEEL / 2, WHEEL / 2], idle: 0.18 },
    pokeOnOpen: true,
  },
  {
    id: 'bk-arch',
    label: 'Grand Army Plaza, Prospect Park',
    art: grandArmyArch,
    w: 3.0,
    h: 3.4,
    x: 2.4,
    z: -3.1,
    order: 0.18,
    seed: 2216,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'bk-park-tree-1',
    label: 'Prospect Park',
    art: (s) => parkTree(s, '#9cbf6a', 'rgba(60,90,40,0.55)'),
    w: 1.5,
    h: 2.5,
    x: 0.8,
    z: -2.7,
    order: 0.24,
    seed: 2217,
    poke: 'tilt',
  },
  {
    id: 'bk-park-tree-2',
    label: 'Prospect Park',
    art: (s) => parkTree(s, '#7fae5e', 'rgba(50,80,35,0.55)'),
    w: 1.5,
    h: 2.5,
    x: 3.9,
    z: -3.6,
    order: 0.24,
    seed: 2218,
    poke: 'tilt',
  },
  {
    id: 'bk-garden',
    label: 'Brooklyn Botanic Garden',
    art: botanicGarden,
    w: 2.9,
    h: 2.4,
    x: 4.45,
    z: -1.6,
    scale: 1.2,
    order: 0.3,
    seed: 2221,
    glow: true,
    poke: 'tilt',
    petals: { from: GARDEN_BLOSSOMS },
    pokeOnOpen: true,
  },
  {
    id: 'bk-mural',
    label: 'Brooklyn street art',
    art: mural,
    w: 2.3,
    h: 4.3,
    x: -6.35,
    z: -1.3,
    ry: 0.6,
    order: 0.26,
    seed: 2204,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'bk-parachute',
    label: 'The Parachute Jump',
    art: parachuteJump,
    w: 1.9,
    h: 5.2,
    x: 6.35,
    z: -1.3,
    ry: -0.6,
    order: 0.26,
    seed: 2205,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'bk-cyclone',
    label: 'The Cyclone',
    art: cyclone,
    w: 4.4,
    h: 2.3,
    x: 4.0,
    z: 1.35,
    scale: 0.85,
    order: 0.7,
    seed: 2206,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'bk-brown',
    label: 'Park Slope brownstones',
    art: (s) => brownstones(s, BROOKLYN_HOUSES.slice(0, 2)),
    w: 3.35,
    h: 3.45,
    x: -3.85,
    z: -0.95,
    order: 0.46,
    seed: 2207,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'bk-cup',
    label: 'Williamsburg coffee',
    art: coffeeCup,
    w: 1.4,
    h: 2.1,
    x: -1.75,
    z: -0.35,
    scale: 1.25,
    order: 0.52,
    seed: 2219,
    poke: 'tilt',
  },
  {
    id: 'bk-carousel',
    label: 'The carousel',
    art: carousel,
    w: 3.0,
    h: 2.5,
    x: 0.4,
    z: 0.7,
    order: 0.6,
    seed: 2208,
    glow: true,
    poke: 'tilt',
    lamp: [1.5, 1.2],
  },
  horse(0, '#f6f0e2', C.red),
  horse(1, '#e9dfc7', '#3f6fb0'),
  horse(2, '#f6f0e2', '#2f9b7a'),
  horse(3, '#efe4d0', '#d06aa6'),
  {
    id: 'bk-barclays',
    label: 'Barclays Center',
    art: barclaysCenter,
    w: 3.4,
    h: 1.9,
    x: -6.05,
    z: 1.0,
    ry: 0.4,
    order: 0.68,
    seed: 2222,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'bk-welcome',
    label: 'Welcome to Brooklyn',
    art: welcomeSign,
    w: 2.6,
    h: 1.75,
    x: -2.95,
    z: 2.05,
    order: 0.72,
    seed: 2209,
    poke: 'tilt',
  },
  {
    id: 'bk-icecream',
    label: 'Ice cream truck',
    art: iceCreamTruck,
    w: 2.1,
    h: 1.65,
    x: 1.6,
    z: 2.4,
    order: 0.76,
    seed: 2215,
    glow: true,
    poke: 'drive',
  },
  {
    id: 'bk-cyclist',
    label: 'A Williamsburg cyclist',
    art: cyclist,
    w: 1.5,
    h: 1.6,
    x: -2.3,
    z: 2.85,
    order: 0.84,
    seed: 2220,
    poke: 'drive',
  },
  {
    id: 'bk-umbrella-1',
    label: 'A day at the beach',
    art: (s) => beachUmbrella(s, C.red),
    w: 1.2,
    h: 1.3,
    x: 4.1,
    z: 3.15,
    order: 0.8,
    seed: 2211,
    poke: 'tilt',
  },
  {
    id: 'bk-umbrella-2',
    label: 'A day at the beach',
    art: (s) => beachUmbrella(s, '#3f6fb0'),
    w: 1.2,
    h: 1.3,
    x: 6.2,
    z: 2.95,
    order: 0.82,
    seed: 2212,
    poke: 'tilt',
  },
  {
    id: 'bk-beach',
    label: 'Beachgoers',
    art: beachgoers,
    w: 1.5,
    h: 1.25,
    x: -0.9,
    z: 3.3,
    scale: 1.2,
    order: 0.88,
    seed: 2213,
    poke: 'tilt',
  },
  {
    id: 'bk-gull',
    label: 'A seagull, eyeing your lunch',
    art: seagull,
    w: 0.7,
    h: 0.5,
    x: 1.0,
    z: 3.0,
    scale: 1.1,
    order: 0.92,
    seed: 2214,
    poke: 'lift',
  },
]
