import { PieceDef } from './pieces'
import { skyBackdrop } from './art-landmarks'
import { cloud, streetLamp } from './art-street'
import { parkTree } from './art-brooklyn'
import {
  belvedereCastle,
  bethesdaFountain,
  bethesdaTerrace,
  bowBridge,
  citiBike,
  ducks,
  gapstowBridge,
  guggenheim,
  hansomCab,
  metMuseum,
  parkSkyline,
  plazaHotel,
  rowboat,
  runners,
  sanRemo,
  squirrel,
} from './art-park'

// Where a park tree's crown is (art units, for a 1.5-wide tree), so its
// leaves can fall from it.
const CROWN: [number, number, number][] = [
  [0.75, 1.45, 0.5],
  [0.75, 1.9, 0.35],
]

const autumnTree = (id: string, x: number, z: number, leaf: string, shadow: string, fall: string[], seed: number, order: number): PieceDef => ({
  id,
  label: 'Autumn in the park',
  art: (s) => parkTree(s, leaf, shadow),
  w: 1.5,
  h: 2.5,
  x,
  z,
  order,
  seed,
  poke: 'tilt',
  petals: { from: CROWN, colors: fall },
})

const GOLD = ['#e6bb4c', '#f0cf6a', '#d99a35']
const RED = ['#c9503a', '#e0703f', '#a8402e']
const ORANGE = ['#e3923f', '#f0b04c', '#c9673a']

// The third spread: Central Park in October, looking south to Midtown.
export const PARK: PieceDef[] = [
  {
    id: 'cp-sky',
    label: 'The sky over the park',
    art: (s) => skyBackdrop(s, false),
    nightArt: (s) => skyBackdrop(s, true),
    w: 11.6,
    h: 7.4,
    x: 0,
    z: -4.75,
    sameArtAs: 'sky',
    order: 0,
    seed: 3101,
    glow: true,
    sky: true,
  },
  {
    id: 'cp-cloud',
    label: 'A cloud',
    art: cloud,
    w: 1.9,
    h: 0.8,
    x: 3.3,
    z: 0,
    parent: 'cp-sky',
    offset: [3.3, 5.6, 0.12],
    sameArtAs: 'cloud-right',
    order: 0,
    seed: 3102,
    padBottom: true,
    bob: { amp: 0.04, speed: 0.5 },
    poke: 'lift',
    sky: true,
  },
  {
    id: 'cp-skyline',
    label: "Billionaires' Row and Midtown",
    art: parkSkyline,
    w: 12.6,
    h: 4.8,
    x: 0,
    z: -4.2,
    order: 0.08,
    seed: 3201,
    glow: true,
  },
  {
    id: 'cp-plaza',
    label: 'The Plaza Hotel',
    art: plazaHotel,
    w: 2.6,
    h: 3.5,
    x: -4.7,
    z: -3.25,
    order: 0.16,
    seed: 3202,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'cp-gapstow',
    label: 'Gapstow Bridge over the Pond',
    art: gapstowBridge,
    w: 3.0,
    h: 1.3,
    x: -2.2,
    z: -2.4,
    order: 0.22,
    seed: 3203,
    poke: 'tilt',
  },
  autumnTree('cp-tree-gold', -0.7, -2.75, '#e6bb4c', 'rgba(150,100,20,0.5)', GOLD, 3301, 0.24),
  autumnTree('cp-tree-red', 3.1, -2.6, '#cf5a3e', 'rgba(120,30,20,0.5)', RED, 3302, 0.24),
  {
    id: 'cp-guggenheim',
    label: 'The Guggenheim, on Fifth Avenue',
    art: guggenheim,
    w: 2.8,
    h: 2.3,
    x: -6.3,
    z: -0.8,
    ry: 0.55,
    order: 0.26,
    seed: 3204,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'cp-sanremo',
    label: 'The San Remo, Central Park West',
    art: sanRemo,
    w: 2.4,
    h: 5.0,
    x: 6.35,
    z: -1.3,
    ry: -0.6,
    order: 0.26,
    seed: 3205,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'cp-terrace',
    label: 'Bethesda Terrace',
    art: bethesdaTerrace,
    w: 4.4,
    h: 2.4,
    x: 0.4,
    z: -1.4,
    order: 0.3,
    seed: 3206,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'cp-bow',
    label: 'Bow Bridge',
    art: bowBridge,
    w: 3.8,
    h: 1.25,
    x: 4.4,
    z: -0.5,
    order: 0.36,
    seed: 3207,
    poke: 'tilt',
  },
  {
    id: 'cp-fountain',
    label: 'Bethesda Fountain and the Angel of the Waters',
    art: bethesdaFountain,
    w: 2.0,
    h: 2.3,
    x: 0.4,
    z: -0.3,
    order: 0.42,
    seed: 3208,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'cp-castle',
    label: 'Belvedere Castle',
    art: belvedereCastle,
    w: 2.2,
    h: 2.7,
    x: -2.7,
    z: 1.1,
    order: 0.55,
    seed: 3209,
    glow: true,
    poke: 'tilt',
    startles: 'cp-squirrel',
  },
  {
    id: 'cp-boat',
    label: 'Rowing on the Lake',
    art: rowboat,
    w: 1.2,
    h: 0.7,
    x: 3.0,
    z: 0.8,
    scale: 1.2,
    order: 0.6,
    seed: 3210,
    bob: { amp: 0.03, speed: 1.3, sway: 0.03 },
    poke: 'drive',
  },
  {
    id: 'cp-ducks',
    label: 'Ducks on the Lake',
    art: ducks,
    w: 1.0,
    h: 0.4,
    x: 5.5,
    z: 1.1,
    order: 0.62,
    seed: 3211,
    bob: { amp: 0.02, speed: 1.7 },
    poke: 'drive',
  },
  {
    id: 'cp-lamp',
    label: 'A park lamppost',
    art: streetLamp,
    w: 0.6,
    h: 2.05,
    x: -0.6,
    z: 1.7,
    sameArtAs: 'lamp-left',
    order: 0.64,
    seed: 3212,
    glow: true,
    poke: 'tilt',
    lamp: [0.42, 1.69],
  },
  autumnTree('cp-tree-orange', -4.6, 1.7, '#e3923f', 'rgba(150,60,20,0.5)', ORANGE, 3303, 0.66),
  autumnTree('cp-tree-gold-2', 4.5, 2.3, '#e6bb4c', 'rgba(150,100,20,0.5)', GOLD, 3304, 0.7),
  {
    id: 'cp-met',
    label: 'The Metropolitan Museum of Art',
    art: metMuseum,
    w: 2.9,
    h: 1.75,
    x: -6.75,
    z: 2.55,
    ry: 0.5,
    order: 0.68,
    seed: 3313,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'cp-squirrel',
    label: 'A squirrel, busy',
    art: squirrel,
    w: 0.6,
    h: 0.5,
    x: -2.5,
    z: 0.95,
    order: 0.72,
    seed: 3213,
    poke: 'run',
    run: {
      path: [
        [-2.5, 0.95],
        [-1.6, 1.4],
        [-1.25, 2.3],
      ],
      face: 1,
    },
    pokeOnOpen: true,
  },
  {
    id: 'cp-bike',
    label: 'A Citi Bike along the park drive',
    art: citiBike,
    w: 1.5,
    h: 1.5,
    x: -3.0,
    z: 3.05,
    order: 0.82,
    seed: 3314,
    glow: true,
    poke: 'drive',
  },
  {
    // A lap of the Reservoir, and back.
    id: 'cp-runners',
    label: 'Runners on the Reservoir loop',
    art: runners,
    w: 1.3,
    h: 1.2,
    x: -1.4,
    z: 3.42,
    order: 0.86,
    seed: 3315,
    poke: 'run',
    run: {
      path: [
        [-1.4, 3.42],
        [0.6, 3.3],
        [3.4, 3.5],
      ],
      face: 1,
    },
  },
  {
    id: 'cp-carriage',
    label: 'A carriage ride',
    art: hansomCab,
    w: 2.6,
    h: 1.35,
    x: 1.6,
    z: 2.5,
    order: 0.8,
    seed: 3214,
    glow: true,
    poke: 'drive',
  },
]
