import { PieceDef } from './pieces'
import { treeFall } from './season'
import { empireState, skyBackdrop } from './art-landmarks'
import { cloud, streetLamp, subwayEntrance } from './art-street'
import { cyclist } from './art-brooklyn'
import { midtownSkyline } from './art-midtown'
import { riverFerry } from './art-dumbo'
import {
  DOMINO_CROWNS,
  buskers,
  dominoPark,
  dominoRefinery,
  hipsters,
  muralWall,
  shopRow,
  smorgasburg,
  treeStand,
  williamsburgBridge,
  wytheHotel,
} from './art-williamsburg'

// Williamsburg: the waterfront looking west over the East River to
// Manhattan at sunset, with Bedford Avenue in front.
export const WILLIAMSBURG: PieceDef[] = [
  {
    id: 'wb-sky',
    label: 'Sunset over Manhattan',
    art: (s) => skyBackdrop(s, false, true),
    nightArt: (s) => skyBackdrop(s, true),
    w: 11.6,
    h: 7.4,
    x: 0,
    z: -4.75,
    sameArtAs: 'bk-sky',
    order: 0,
    seed: 9101,
    glow: true,
    sky: true,
  },
  {
    id: 'wb-cloud',
    label: 'A cloud',
    art: cloud,
    w: 1.9,
    h: 0.8,
    x: -3.0,
    z: 0,
    parent: 'wb-sky',
    offset: [-3.0, 5.5, 0.12],
    sameArtAs: 'cloud-right',
    order: 0,
    seed: 9102,
    padBottom: true,
    bob: { amp: 0.04, speed: 0.5 },
    poke: 'lift',
    sky: true,
  },
  {
    id: 'wb-far',
    label: 'Manhattan, across the river',
    art: midtownSkyline,
    w: 12.6,
    h: 4.5,
    x: 0,
    z: -4.25,
    sameArtAs: 'md-skyline',
    order: 0.08,
    seed: 9103,
    glow: true,
  },
  {
    id: 'wb-esb',
    label: 'The Empire State Building, far off',
    art: empireState,
    w: 2.6,
    h: 7.0,
    x: 2.2,
    z: -4.0,
    scale: 0.72,
    sameArtAs: 'esb',
    order: 0.1,
    seed: 9104,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'wb-bridge',
    label: 'The Williamsburg Bridge',
    art: williamsburgBridge,
    w: 6.4,
    h: 3.5,
    x: -3.6,
    z: -3.15,
    order: 0.14,
    seed: 9105,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'wb-ferry',
    label: 'The ferry, calling at North Williamsburg',
    art: riverFerry,
    w: 2.2,
    h: 0.85,
    x: 3.4,
    z: -2.65,
    sameArtAs: 'du-ferry',
    order: 0.22,
    seed: 9106,
    glow: true,
    bob: { amp: 0.025, speed: 1.0, sway: 0.015 },
    poke: 'drive',
  },
  {
    id: 'wb-domino',
    label: 'The Domino Sugar Refinery',
    art: dominoRefinery,
    w: 2.4,
    h: 4.6,
    x: -6.4,
    z: -0.7,
    ry: 0.6,
    order: 0.26,
    seed: 9107,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'wb-wythe',
    label: 'The Wythe Hotel',
    art: wytheHotel,
    w: 2.2,
    h: 3.9,
    x: 6.4,
    z: -0.7,
    ry: -0.6,
    order: 0.26,
    seed: 9108,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'wb-park',
    label: 'Domino Park and its yellow walkway',
    art: dominoPark,
    w: 3.0,
    h: 1.5,
    x: -3.3,
    z: -1.75,
    order: 0.3,
    seed: 9109,
    glow: true,
    poke: 'tilt',
    petals: { from: DOMINO_CROWNS, colors: treeFall(['#d98b3c', '#e6bb4c', '#c9673a']) },
  },
  {
    id: 'wb-market',
    label: 'Smorgasburg, on a Saturday',
    art: smorgasburg,
    w: 3.4,
    h: 1.6,
    x: 2.6,
    z: -1.4,
    // It moves indoors for the winter.
    seasons: ['spring', 'summer', 'autumn'],
    order: 0.32,
    seed: 9110,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'wb-trees',
    label: 'Christmas trees for sale',
    art: treeStand,
    w: 3.0,
    h: 1.3,
    x: 2.6,
    z: -1.4,
    seasons: ['winter'],
    order: 0.32,
    seed: 9111,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'wb-mural',
    label: 'Street art on Wythe Avenue',
    art: muralWall,
    w: 2.4,
    h: 1.6,
    x: -0.5,
    z: -0.45,
    order: 0.4,
    seed: 9112,
    poke: 'tilt',
  },
  {
    id: 'wb-station',
    label: 'Bedford Av, on the L',
    art: (s) => subwayEntrance(s, { name: 'BEDFORD AV', lines: [['L', '#a7a9ac', '#ffffff']] }),
    w: 1.7,
    h: 1.42,
    x: -4.6,
    z: 1.6,
    order: 0.58,
    seed: 9113,
    glow: true,
    poke: 'tilt',
    lamp: [0.14, 1.29],
    lampColor: '#9dffb0',
  },
  {
    id: 'wb-shops',
    label: 'Records, vintage and coffee on Bedford Avenue',
    art: shopRow,
    w: 3.2,
    h: 2.4,
    x: 3.0,
    z: 1.3,
    order: 0.62,
    seed: 9114,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'wb-lamp',
    label: 'A street lamp',
    art: streetLamp,
    w: 0.6,
    h: 2.05,
    x: 0.6,
    z: 1.5,
    sameArtAs: 'lamp-left',
    order: 0.64,
    seed: 9115,
    glow: true,
    poke: 'tilt',
    lamp: [0.42, 1.69],
  },
  {
    id: 'wb-buskers',
    label: 'Buskers on the corner',
    art: buskers,
    w: 1.6,
    h: 1.3,
    x: -1.7,
    z: 2.3,
    scale: 1.1,
    order: 0.74,
    seed: 9116,
    poke: 'lift',
  },
  {
    id: 'wb-hipsters',
    label: 'Out on Bedford Avenue',
    art: hipsters,
    w: 1.5,
    h: 1.55,
    x: 1.0,
    z: 2.9,
    scale: 1.1,
    order: 0.8,
    seed: 9117,
    poke: 'tilt',
  },
  {
    id: 'wb-cyclist',
    label: 'A Williamsburg cyclist',
    art: cyclist,
    w: 1.5,
    h: 1.6,
    x: 5.0,
    z: 3.05,
    sameArtAs: 'bk-cyclist',
    order: 0.84,
    seed: 9118,
    poke: 'drive',
  },
]
