import { PieceDef } from './pieces'
import { treeFall } from './season'
import { brooklynBridge, skyBackdrop } from './art-landmarks'
import { farSkyline } from './art-buildings'
import { cloud, dogWalker, readerAndKid, streetLamp } from './art-street'
import { cyclist, iceCreamTruck, seagull } from './art-brooklyn'
import {
  CLOCK,
  PARK_CROWNS,
  bridgePark,
  clockHands,
  clockTower,
  empireStores,
  iceCreamQueue,
  janesCarousel,
  manhattanBridge,
  outdoorCinema,
  pizzeria,
  riverFerry,
  selfieTourists,
  timeOutMarket,
  weddingShoot,
} from './art-dumbo'

const HANDS = 0.56

// DUMBO: the waterfront between the bridges, looking across the East River
// to Lower Manhattan at golden hour.
export const DUMBO: PieceDef[] = [
  {
    id: 'du-sky',
    label: 'Golden hour over the East River',
    art: (s) => skyBackdrop(s, false, true),
    nightArt: (s) => skyBackdrop(s, true),
    w: 11.6,
    h: 7.4,
    x: 0,
    z: -4.75,
    sameArtAs: 'bk-sky',
    order: 0,
    seed: 7101,
    glow: true,
    sky: true,
  },
  {
    id: 'du-cloud',
    label: 'A cloud',
    art: cloud,
    w: 1.9,
    h: 0.8,
    x: 2.6,
    z: 0,
    parent: 'du-sky',
    offset: [2.6, 5.4, 0.12],
    sameArtAs: 'cloud-left',
    order: 0,
    seed: 7102,
    padBottom: true,
    bob: { amp: 0.04, speed: 0.45 },
    poke: 'lift',
    sky: true,
  },
  {
    id: 'du-far',
    label: 'Lower Manhattan, across the river',
    art: farSkyline,
    w: 12.6,
    h: 5.0,
    x: 0,
    z: -4.25,
    sameArtAs: 'far',
    order: 0.08,
    seed: 7103,
    glow: true,
  },
  {
    id: 'du-brooklyn-bridge',
    label: 'The Brooklyn Bridge',
    art: brooklynBridge,
    w: 5.0,
    h: 2.7,
    x: -3.7,
    z: -3.0,
    scale: 1.3,
    sameArtAs: 'bridge',
    order: 0.14,
    seed: 7104,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'du-manhattan-bridge',
    label: 'The Manhattan Bridge',
    art: manhattanBridge,
    w: 6.0,
    h: 3.7,
    x: 3.5,
    z: -3.1,
    order: 0.14,
    seed: 7201,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'du-ferry',
    label: 'A ferry on the East River',
    art: riverFerry,
    w: 2.2,
    h: 0.85,
    x: 2.0,
    z: -2.25,
    order: 0.24,
    seed: 7202,
    glow: true,
    bob: { amp: 0.025, speed: 1.0, sway: 0.015 },
    poke: 'drive',
  },
  {
    id: 'du-clock',
    label: 'The Clock Tower',
    art: clockTower,
    w: 2.0,
    h: 4.5,
    x: -6.4,
    z: -0.6,
    ry: 0.6,
    order: 0.26,
    seed: 7203,
    glow: true,
    poke: 'tilt',
    startles: 'du-hands',
  },
  {
    id: 'du-hands',
    label: 'The Clock Tower’s clock (time flies)',
    art: clockHands,
    w: HANDS,
    h: HANDS,
    x: -6.4,
    z: 0,
    parent: 'du-clock',
    offset: [CLOCK.x - 1.0, CLOCK.y - HANDS / 2, 0.04],
    order: 0.26,
    seed: 7204,
    glow: true,
    padBottom: true,
    poke: 'spin',
    spin: { at: [HANDS / 2, HANDS / 2], idle: 0.08 },
  },
  {
    id: 'du-stores',
    label: 'Empire Stores',
    art: empireStores,
    w: 2.2,
    h: 3.5,
    x: 6.4,
    z: -0.6,
    ry: -0.6,
    order: 0.26,
    seed: 7205,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'du-park',
    label: 'Brooklyn Bridge Park',
    art: bridgePark,
    w: 2.7,
    h: 1.25,
    x: 4.6,
    z: -1.75,
    scale: 1.3,
    // Summer evenings it's a cinema instead.
    seasons: ['spring', 'autumn', 'winter'],
    order: 0.3,
    seed: 8115,
    poke: 'tilt',
    petals: { from: PARK_CROWNS, colors: treeFall(['#e0a040', '#d98b3c', '#c9583a']) },
  },
  {
    id: 'du-cinema',
    label: 'Movies With A View, out on the lawn',
    art: outdoorCinema,
    w: 2.7,
    h: 1.3,
    x: 4.6,
    z: -1.75,
    scale: 1.3,
    seasons: ['summer'],
    order: 0.3,
    seed: 8120,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'du-carousel',
    label: 'Jane’s Carousel, in its glass box',
    art: janesCarousel,
    w: 2.8,
    h: 1.6,
    x: -0.4,
    z: -1.5,
    order: 0.32,
    seed: 7206,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'du-gull',
    label: 'A seagull on the rocks',
    art: seagull,
    w: 0.7,
    h: 0.5,
    x: -4.0,
    z: -1.7,
    scale: 1.1,
    sameArtAs: 'bk-gull',
    order: 0.36,
    seed: 7207,
    poke: 'lift',
  },
  {
    id: 'du-wedding',
    label: 'A wedding shoot on the waterfront',
    art: weddingShoot,
    w: 1.6,
    h: 1.3,
    x: -2.5,
    z: 0.4,
    order: 0.5,
    seed: 7208,
    glow: true,
    poke: 'lift',
  },
  {
    id: 'du-lamp',
    label: 'A street lamp on the cobbles',
    art: streetLamp,
    w: 0.6,
    h: 2.05,
    x: 0.7,
    z: 0.9,
    sameArtAs: 'lamp-left',
    order: 0.56,
    seed: 7209,
    glow: true,
    poke: 'tilt',
    lamp: [0.42, 1.69],
  },
  {
    id: 'du-pizza',
    label: 'The line for pizza',
    art: pizzeria,
    w: 3.0,
    h: 1.8,
    x: 3.1,
    z: 1.0,
    order: 0.62,
    seed: 7210,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'du-timeout',
    label: 'Time Out Market, in Empire Stores',
    art: timeOutMarket,
    w: 2.3,
    h: 1.92,
    x: 6.0,
    z: 0.8,
    order: 0.6,
    seed: 8116,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'du-dog',
    label: 'A walk along Water Street',
    art: dogWalker,
    w: 1.8,
    h: 1.75,
    x: -4.4,
    z: 2.2,
    scale: 1.15,
    sameArtAs: 'dog',
    order: 0.74,
    seed: 7212,
    poke: 'tilt',
  },
  {
    id: 'du-balloon',
    label: 'A red balloon by the river',
    art: readerAndKid,
    w: 1.6,
    h: 1.85,
    x: -6.3,
    z: 2.9,
    scale: 1.15,
    sameArtAs: 'kid',
    order: 0.78,
    seed: 7213,
    poke: 'tilt',
  },
  {
    id: 'du-cyclist',
    label: 'A cyclist bumping over the cobbles',
    art: cyclist,
    w: 1.5,
    h: 1.6,
    x: -1.0,
    z: 2.6,
    sameArtAs: 'bk-cyclist',
    order: 0.8,
    seed: 7211,
    poke: 'drive',
  },
  {
    id: 'du-icecream',
    label: 'Ice cream truck',
    art: iceCreamTruck,
    w: 2.1,
    h: 1.65,
    x: 6.65,
    z: 2.55,
    sameArtAs: 'bk-icecream',
    order: 0.74,
    seed: 8117,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'du-queue',
    label: 'The line for ice cream',
    art: iceCreamQueue,
    w: 1.6,
    h: 1.1,
    x: 4.75,
    z: 2.8,
    order: 0.76,
    seed: 8118,
    poke: 'tilt',
  },
  {
    id: 'du-selfie',
    label: 'A selfie with the Manhattan Bridge',
    art: selfieTourists,
    w: 1.1,
    h: 1.56,
    x: 3.0,
    z: 3.05,
    order: 0.82,
    seed: 8119,
    glow: true,
    poke: 'lift',
  },
]
