import { PieceDef } from './pieces'
import { skyBackdrop, oneWorldTrade } from './art-landmarks'
import { cloud, commuters, streetLamp } from './art-street'
import { seagull } from './art-brooklyn'
import {
  BOARD,
  ROTOR,
  castleClinton,
  chargingBull,
  downtownSkyline,
  eightSpruce,
  fearlessGirl,
  heliRotor,
  helicopter,
  memorial,
  oculus,
  statenFerry,
  stockBoard,
  stockExchange,
  tallShip,
  trinityChurch,
  woolworth,
} from './art-lower'

// Quotes for the stock board: symbol, price, change.
const QUOTES: [string, number, number][] = [
  ['BAGL', 4.2, 0.35],
  ['SLCE', 1.0, 0.05],
  ['CABS', 7.85, -0.42],
  ['DELI', 12.4, 0.9],
  ['RATS', 0.25, -0.03],
  ['BODG', 3.5, 0.21],
  ['HTDG', 2.75, 0.15],
  ['PRTZ', 2.0, -0.12],
  ['LOX', 18.6, 1.1],
  ['MTRO', 2.9, -0.08],
]

const HELI = { x: -4.1, y: 4.75 }

// The fifth spread: Lower Manhattan, seen from the harbour looking north.
export const LOWER: PieceDef[] = [
  {
    id: 'lm-sky',
    label: 'Morning over the Financial District',
    art: (s) => skyBackdrop(s, false),
    nightArt: (s) => skyBackdrop(s, true),
    w: 11.6,
    h: 7.4,
    x: 0,
    z: -4.75,
    sameArtAs: 'sky',
    order: 0,
    seed: 5101,
    glow: true,
    sky: true,
  },
  {
    id: 'lm-cloud',
    label: 'A cloud',
    art: cloud,
    w: 1.9,
    h: 0.8,
    x: 3.4,
    z: 0,
    parent: 'lm-sky',
    offset: [3.4, 5.3, 0.12],
    sameArtAs: 'cloud-left',
    order: 0,
    seed: 5102,
    padBottom: true,
    bob: { amp: 0.04, speed: 0.45 },
    poke: 'lift',
    sky: true,
  },
  {
    id: 'lm-heli',
    label: 'A sightseeing helicopter over the harbor',
    art: helicopter,
    w: 1.5,
    h: 0.72,
    x: HELI.x,
    z: 0,
    parent: 'lm-sky',
    offset: [HELI.x, HELI.y, 0.24],
    order: 0,
    seed: 5103,
    padBottom: true,
    glow: true,
    bob: { amp: 0.07, speed: 1.4, sway: 0.035 },
    poke: 'lift',
  },
  {
    id: 'lm-rotor',
    label: 'A sightseeing helicopter over the harbor',
    art: heliRotor,
    w: 1.7,
    h: 0.12,
    x: HELI.x + ROTOR.x - 0.75,
    z: 0,
    parent: 'lm-heli',
    offset: [ROTOR.x - 0.75, ROTOR.y - 0.06, 0.02],
    order: 0,
    seed: 5104,
    padBottom: true,
    whirl: 11,
  },
  {
    id: 'lm-skyline',
    label: 'The Financial District',
    art: downtownSkyline,
    w: 12.6,
    h: 4.4,
    x: 0,
    z: -4.25,
    order: 0.08,
    seed: 5201,
    glow: true,
  },
  {
    id: 'lm-wtc',
    label: 'One World Trade Center',
    art: oneWorldTrade,
    w: 1.5,
    h: 7.35,
    x: -2.4,
    z: -3.6,
    sameArtAs: 'wtc',
    order: 0.12,
    seed: 5202,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'lm-memorial',
    label: 'The 9/11 Memorial: two pools where the towers stood',
    art: memorial,
    w: 1.9,
    h: 1.02,
    x: -4.85,
    z: -2.45,
    order: 0.17,
    seed: 5216,
    glow: true,
  },
  {
    id: 'lm-oculus',
    label: 'The Oculus',
    art: oculus,
    w: 3.4,
    h: 2.0,
    x: -2.2,
    z: -2.3,
    order: 0.2,
    seed: 5203,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'lm-trinity',
    label: 'Trinity Church, at the head of Wall Street',
    art: trinityChurch,
    w: 1.6,
    h: 3.7,
    x: 0.7,
    z: -2.0,
    order: 0.24,
    seed: 5204,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'lm-woolworth',
    label: 'The Woolworth Building',
    art: woolworth,
    w: 1.7,
    h: 5.5,
    x: -6.4,
    z: -1.1,
    ry: 0.6,
    order: 0.26,
    seed: 5205,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'lm-spruce',
    label: '8 Spruce Street',
    art: eightSpruce,
    w: 1.7,
    h: 5.3,
    x: 6.4,
    z: -1.1,
    ry: -0.6,
    order: 0.26,
    seed: 5206,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'lm-nyse',
    label: 'The New York Stock Exchange',
    art: stockExchange,
    w: 3.2,
    h: 2.5,
    x: 3.3,
    z: -1.2,
    order: 0.34,
    seed: 5207,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'lm-board',
    label: 'The stock board on Broad Street',
    art: stockBoard,
    w: 1.6,
    h: 1.05,
    x: 5.35,
    z: -0.45,
    order: 0.4,
    seed: 5217,
    glow: true,
    poke: 'tilt',
    ticker: {
      text: QUOTES.map(([sym, price, change]): [string, string] => [
        `${sym} ${price.toFixed(2)} ${change >= 0 ? '▲' : '▼'}${Math.abs(change).toFixed(2)}   `,
        change >= 0 ? '#5fe08a' : '#ff6b6b',
      ]),
      at: [BOARD.x, BOARD.y],
      w: BOARD.w,
      h: BOARD.h,
    },
  },
  {
    id: 'lm-lamp',
    label: 'A street lamp',
    art: streetLamp,
    w: 0.6,
    h: 2.05,
    x: -2.9,
    z: 0.9,
    sameArtAs: 'lamp-left',
    order: 0.5,
    seed: 5208,
    glow: true,
    poke: 'tilt',
    lamp: [0.42, 1.69],
  },
  {
    id: 'lm-bull',
    label: 'The Charging Bull',
    art: chargingBull,
    w: 2.0,
    h: 1.2,
    x: -0.9,
    z: 1.0,
    order: 0.56,
    seed: 5209,
    poke: 'drive',
  },
  {
    id: 'lm-girl',
    label: 'Fearless Girl (not budging)',
    art: fearlessGirl,
    w: 0.6,
    h: 1.0,
    x: 1.25,
    z: 1.15,
    scale: 1.3,
    order: 0.58,
    seed: 5210,
    poke: 'tilt',
  },
  {
    id: 'lm-commuters',
    label: 'Wall Street, at lunch',
    art: commuters,
    w: 1.6,
    h: 1.35,
    x: 3.6,
    z: 1.2,
    scale: 1.3,
    sameArtAs: 'commuters',
    order: 0.62,
    seed: 5211,
    poke: 'tilt',
  },
  {
    id: 'lm-castle',
    label: 'Castle Clinton, in Battery Park',
    art: castleClinton,
    w: 2.6,
    h: 1.0,
    x: -4.4,
    z: 2.5,
    order: 0.7,
    seed: 5212,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'lm-ship',
    label: 'A tall ship at the Seaport',
    art: tallShip,
    w: 2.0,
    h: 2.4,
    x: 6.3,
    z: 2.6,
    order: 0.74,
    seed: 5213,
    glow: true,
    bob: { amp: 0.03, speed: 0.8, sway: 0.02 },
    poke: 'lift',
  },
  {
    id: 'lm-ferry',
    label: 'The Staten Island Ferry',
    art: statenFerry,
    w: 2.9,
    h: 1.1,
    x: 2.8,
    z: 3.9,
    order: 0.82,
    seed: 5214,
    glow: true,
    bob: { amp: 0.03, speed: 1.1, sway: 0.015 },
    poke: 'drive',
  },
  {
    id: 'lm-gull',
    label: 'A seagull, following the ferry',
    art: seagull,
    w: 0.7,
    h: 0.5,
    x: 0.4,
    z: 3.4,
    scale: 1.1,
    sameArtAs: 'bk-gull',
    order: 0.86,
    seed: 5215,
    poke: 'lift',
  },
]
