import { PieceDef } from './pieces'
import { chrysler, skyBackdrop } from './art-landmarks'
import { cloud, streetLamp, taxi } from './art-street'
import {
  grandCentral,
  libraryLion,
  midtownSkyline,
  publicLibrary,
  radioCity,
  rockRink,
  skater,
  stPatricks,
  thirtyRock,
  tourBus,
} from './art-midtown'

const skaterPiece = (id: string, x: number, z: number, coat: string, scarf: string, seed: number, show = false): PieceDef => ({
  id,
  label: 'A skater on the rink',
  art: (s) => skater(s, coat, scarf),
  w: 0.6,
  h: 1.0,
  x,
  z,
  order: 0.4,
  seed,
  poke: 'twirl',
  pokeOnOpen: show,
})

const lion = (id: string, label: string, x: number, face: 1 | -1, seed: number): PieceDef => ({
  id,
  label,
  art: (s) => libraryLion(s, face),
  w: 0.9,
  h: 0.7,
  x,
  z: 2.2,
  scale: 1.4,
  order: 0.62,
  seed,
  poke: 'lift',
})

// The sixth spread: Midtown, looking north up Fifth Avenue.
export const MIDTOWN: PieceDef[] = [
  {
    id: 'md-sky',
    label: 'The sky over Midtown',
    art: (s) => skyBackdrop(s, false),
    nightArt: (s) => skyBackdrop(s, true),
    w: 11.6,
    h: 7.4,
    x: 0,
    z: -4.75,
    sameArtAs: 'sky',
    order: 0,
    seed: 6101,
    glow: true,
    sky: true,
  },
  {
    id: 'md-cloud',
    label: 'A cloud',
    art: cloud,
    w: 1.9,
    h: 0.8,
    x: 3.6,
    z: 0,
    parent: 'md-sky',
    offset: [3.6, 5.5, 0.12],
    sameArtAs: 'cloud-right',
    order: 0,
    seed: 6102,
    padBottom: true,
    bob: { amp: 0.04, speed: 0.5 },
    poke: 'lift',
    sky: true,
  },
  {
    id: 'md-skyline',
    label: 'Park Avenue and beyond',
    art: midtownSkyline,
    w: 12.6,
    h: 4.5,
    x: 0,
    z: -4.25,
    order: 0.08,
    seed: 6201,
    glow: true,
  },
  {
    id: 'md-rock',
    label: '30 Rockefeller Plaza',
    art: thirtyRock,
    w: 2.0,
    h: 6.4,
    x: -1.2,
    z: -3.4,
    order: 0.12,
    seed: 6202,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'md-stpat',
    label: "St. Patrick's Cathedral",
    art: stPatricks,
    w: 2.3,
    h: 4.0,
    x: 1.6,
    z: -2.8,
    order: 0.18,
    seed: 6203,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'md-radio',
    label: 'Radio City Music Hall',
    art: radioCity,
    w: 2.0,
    h: 4.4,
    x: -6.4,
    z: -1.0,
    ry: 0.6,
    order: 0.24,
    seed: 6204,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'md-chrysler',
    label: 'The Chrysler Building',
    art: chrysler,
    w: 2.0,
    h: 6.3,
    x: 6.4,
    z: -1.7,
    ry: -0.6,
    sameArtAs: 'chrysler',
    order: 0.24,
    seed: 6205,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'md-rink',
    label: 'The rink at Rockefeller Center',
    art: rockRink,
    w: 3.6,
    h: 1.5,
    x: -1.2,
    z: -1.9,
    order: 0.3,
    seed: 6206,
    glow: true,
    poke: 'tilt',
  },
  skaterPiece('md-skater-1', -1.9, -1.25, '#c8202f', '#f7c948', 6207, true),
  skaterPiece('md-skater-2', -0.5, -1.05, '#2a4fb0', '#f4f1ea', 6208),
  {
    id: 'md-gc',
    label: 'Grand Central Terminal',
    art: grandCentral,
    w: 3.6,
    h: 2.7,
    x: 3.9,
    z: 0.3,
    order: 0.5,
    seed: 6209,
    glow: true,
    poke: 'tilt',
  },
  {
    id: 'md-library',
    label: 'The New York Public Library',
    art: publicLibrary,
    w: 3.4,
    h: 2.0,
    x: -4.1,
    z: 1.1,
    order: 0.56,
    seed: 6210,
    glow: true,
    poke: 'tilt',
  },
  lion('md-lion-patience', 'Patience, one of the library lions', -5.25, -1, 6211),
  lion('md-lion-fortitude', 'Fortitude, the other library lion', -2.95, 1, 6212),
  {
    id: 'md-lamp',
    label: 'A Fifth Avenue lamp',
    art: streetLamp,
    w: 0.6,
    h: 2.05,
    x: -1.4,
    z: 1.9,
    sameArtAs: 'lamp-left',
    order: 0.66,
    seed: 6213,
    glow: true,
    poke: 'tilt',
    lamp: [0.42, 1.69],
  },
  {
    id: 'md-bus',
    label: 'A sightseeing bus up Fifth Avenue',
    art: tourBus,
    w: 2.9,
    h: 1.55,
    x: 0.5,
    z: 2.8,
    order: 0.8,
    seed: 6214,
    glow: true,
    poke: 'drive',
  },
  {
    id: 'md-cab',
    label: 'Yellow cab',
    art: taxi,
    w: 2.0,
    h: 0.95,
    x: 4.6,
    z: 3.2,
    sameArtAs: 'taxi',
    order: 0.84,
    seed: 6215,
    glow: true,
    poke: 'drive',
  },
]
