import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export interface Link {
  href: string;
  label: string;
  key?: string;
}

const Home: NextPage = () => {
  const links: Link[] = [
    { href: "/", label: "Home" },
    { href: "blog", label: "Blog" },
    { href: "https://www.youtube.com/kuzeykose", label: "YouTube" },
  ].map((link: Link) => {
    link.key = `nav-link-${link.href}-${link.label}`;
    return link;
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          maxWidth: "850px",
          width: "100%",
          margin: "0 auto",
        }}
      >
        <nav>
          <ul
            style={{
              display: "flex",
              justifyContent: "center",
              listStyle: "none",
            }}
          >
            {links.map(({ key, href, label }) => (
              <li key={key} style={{ margin: 2 }}>
                {label === "YouTube" ? (
                  <a href={href} target="_blank">
                    <button>{label}</button>
                  </a>
                ) : (
                  <Link href={href}>
                    <button>{label}</button>
                  </Link>
                )}
              </li>
            ))}{" "}
          </ul>
        </nav>
      </div>
    </div>
  );
};

export default Home;
